/** Tokens del diseño "Executive Stature" (Stitch) — reproducción fiel */
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#48473f',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#ebc166',
        'tertiary-fixed': '#e6e2d7',
        secondary: '#795902',
        'surface-container-low': '#f0f3ff',
        'surface-container-highest': '#d8e3fa',
        'on-primary-fixed': '#0a1a3a',
        'outline-variant': '#c5c6cf',
        'on-surface-variant': '#45464e',
        'inverse-on-surface': '#ebf1ff',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'primary-container': '#1b2a4a',
        'surface-variant': '#d8e3fa',
        'surface-tint': '#4f5e81',
        'surface-dim': '#cfdaf1',
        background: '#f9f9ff',
        'primary-fixed': '#d9e2ff',
        outline: '#75777f',
        'on-tertiary-fixed': '#1c1c15',
        'inverse-surface': '#263142',
        'on-secondary-fixed-variant': '#5b4300',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#384668',
        primary: '#041534',
        'on-tertiary-container': '#959289',
        'primary-fixed-dim': '#b7c6ee',
        'on-background': '#111c2c',
        'on-error-container': '#93000a',
        'secondary-fixed': '#ffdf9e',
        'tertiary-fixed-dim': '#cac6bc',
        'on-secondary-container': '#775800',
        'surface-bright': '#f9f9ff',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#b7c6ee',
        tertiary: '#171710',
        'secondary-container': '#fdd275',
        'tertiary-container': '#2c2b24',
        error: '#ba1a1a',
        'surface-container-high': '#dee8ff',
        surface: '#f9f9ff',
        'surface-container': '#e7eeff',
        'on-surface': '#111c2c',
        'on-secondary-fixed': '#261a00',
        'on-primary-container': '#8392b7',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '20px',
        gutter: '24px',
        'section-gap-desktop': '160px',
        'container-max': '1280px',
        'section-gap-mobile': '80px',
        unit: '8px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Sora', 'sans-serif'],
        'display-xl-mobile': ['Sora', 'sans-serif'],
        'headline-md': ['Sora', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Sora', 'sans-serif'],
        'display-xl': ['Sora', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-xl-mobile': ['48px', { lineHeight: '52px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '26px', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '32px', letterSpacing: '0', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-xl': ['72px', { lineHeight: '80px', letterSpacing: '-0.04em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
